language: python
python:
    - "2.7"
services:
    - mysql
env:
    -DJANGO=1.11 DB=mysql
install:
    - pip install -r tests_requirements.txt
before_script:
    - mysql -e 'create database test;' -u root
script:
    - python django_app/manage.py test user_authentication
    - coverage run --source=django_app/ manage.py test django_app/user_authentication
after_success: coveralls