language: python
python:
    - "2.7"
services:
    - mysql
env:
    -DJANGO=1.11 DB=mysql
install:
    - pip install -r tests_requirements.txt
before_script:
    - mysql -e 'create database test;' -u root
script:
    - python manage.py test user_authentication notes groups kalendar grades
    - coverage run --source=django_app,user_authentication,notes,groups,kalendar,grades manage.py test
after_success: coveralls
