language: python
python:
    - "2.7"
services:
    - postgresql
env:
    -DJANGO=1.11 DB=mysql
install:
    - pip install -r tests_requirements.txt
before_script:
    - psql -c 'create database test;' -U postgres
script:
    - python manage.py test user_authentication notes kalendar grades notice_board poll
    - coverage run --source=django_app,user_authentication,notes,kalendar,grades,notice_board,poll manage.py test
after_success: coveralls
