# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(choices=[('MMF I', 'Matematyczne Metody Fizyki'), ('PP', 'Programowanie Proceduralne'), ('MI', 'Matematyka I')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Field_of_study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldOfStudy', models.CharField(choices=[('FT', 'Fizyka Techniczna'), ('FM', 'Fizyka Medyczna'), ('IS', 'Informatyka Stosowana')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('I', 'rok I'), ('II', 'rok II'), ('III', 'rok III'), ('IV', 'rok IV'), ('V', 'rok V')], max_length=1)),
                ('classes', models.ManyToManyField(to='grades.Classes')),
                ('field_of_study', models.ManyToManyField(to='grades.Field_of_study')),
            ],
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
    ]
