# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20171202_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ManyToManyField(to='grades.Classes')),
                ('fieldOfStudy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Field_of_study')),
            ],
        ),
        migrations.RenameField(
            model_name='year',
            old_name='field_of_study',
            new_name='fieldOfStudy',
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Year'),
        ),
    ]
