# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_auto_20171202_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='year',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='year',
            name='fieldOfStudy',
        ),
        migrations.AlterField(
            model_name='classes',
            name='classes',
            field=models.CharField(choices=[('MMF I', 'Matematyczne Metody Fizyki'), ('PP', 'Programowanie Proceduralne'), ('MI', 'Matematyka I')], max_length=10),
        ),
        migrations.AlterField(
            model_name='field_of_study',
            name='fieldOfStudy',
            field=models.CharField(choices=[('FT', 'Fizyka Techniczna'), ('FM', 'Fizyka Medyczna'), ('IS', 'Informatyka Stosowana')], max_length=10),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(choices=[('I', 'rok I'), ('II', 'rok II'), ('III', 'rok III'), ('IV', 'rok IV'), ('V', 'rok V')], max_length=2),
        ),
        migrations.AddField(
            model_name='grades_group',
            name='classes',
            field=models.ManyToManyField(to='grades.Classes'),
        ),
        migrations.AddField(
            model_name='grades_group',
            name='fieldOfStudy',
            field=models.ManyToManyField(to='grades.Field_of_study'),
        ),
        migrations.AddField(
            model_name='grades_group',
            name='year',
            field=models.ManyToManyField(to='grades.Year'),
        ),
    ]
