# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_auto_20171202_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='grades.Year'),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(choices=[('I', 'rok I'), ('II', 'rok II'), ('III', 'rok III'), ('IV', 'rok IV'), ('V', 'rok V')], max_length=3),
        ),
    ]
