# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_auto_20171202_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.Year'),
        ),
    ]
