# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_auto_20171202_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(choices=[('I', 'year I'), ('II', 'year II'), ('III', 'year III'), ('IV', 'year IV'), ('V', 'year V')], max_length=3),
        ),
    ]
