# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_auto_20171203_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fieldOfStudy',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
