# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 16:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0009_auto_20171211_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades_group',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classes',
            name='classes',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='field_of_study',
            name='fieldOfStudy',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='grades_group',
            name='fieldOfStudy',
        ),
        migrations.AddField(
            model_name='grades_group',
            name='fieldOfStudy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.Field_of_study'),
        ),
        migrations.RemoveField(
            model_name='grades_group',
            name='year',
        ),
        migrations.AddField(
            model_name='grades_group',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.Year'),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(max_length=15),
        ),
    ]
