# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-14 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0010_auto_20180106_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradesDict', models.CharField(max_length=500, null=True, verbose_name='grades dictionary')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.Grades_group')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='full name')),
            ],
        ),
    ]
