# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='day')),
                ('start_time', models.TimeField(verbose_name='starting_time')),
                ('end_time', models.TimeField(verbose_name='ending_time')),
                ('notes', models.TextField(verbose_name='personal_notes')),
            ],
        ),
    ]
