# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0002_auto_20171130_2354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'scheduling', 'verbose_name_plural': 'scheduling'},
        ),
    ]
