# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0003_auto_20171201_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='ending_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='notes',
            new_name='personal_notes',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='starting_time',
        ),
    ]
