# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kalendar', '0004_auto_20171202_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='title'),
            preserve_default=False,
        ),
    ]
