# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('lecture_number', models.IntegerField()),
                ('lecture_title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='NoteText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('lecture_number', models.IntegerField()),
                ('lecture_title', models.CharField(max_length=250)),
                ('content', models.FileField(upload_to='textfiles/')),
            ],
        ),
    ]
