# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_noteimage_notetext'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('lecture_number', models.IntegerField()),
                ('lecture_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='NoteImage',
        ),
        migrations.DeleteModel(
            name='NoteText',
        ),
        migrations.CreateModel(
            name='NoteFileImage',
            fields=[
                ('notefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.NoteFile')),
                ('image', models.ImageField(upload_to='images/')),
            ],
            bases=('notes.notefile',),
        ),
        migrations.CreateModel(
            name='NoteFileOther',
            fields=[
                ('notefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.NoteFile')),
                ('content', models.FileField(upload_to='other/')),
            ],
            bases=('notes.notefile',),
        ),
        migrations.CreateModel(
            name='NoteFilePdf',
            fields=[
                ('notefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.NoteFile')),
                ('content', models.FileField(upload_to='pdfs/')),
            ],
            bases=('notes.notefile',),
        ),
        migrations.CreateModel(
            name='NoteFileText',
            fields=[
                ('notefile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.NoteFile')),
                ('content', models.FileField(upload_to='textfiles/')),
            ],
            bases=('notes.notefile',),
        ),
    ]
