# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20171210_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default='', max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='lecture_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='lecture_title',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
