# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0010_auto_20180106_1638'),
        ('notes', '0005_auto_20171212_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_number', models.IntegerField()),
                ('lecture_title', models.CharField(max_length=250)),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.Classes')),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='lecture_number',
        ),
        migrations.RemoveField(
            model_name='note',
            name='lecture_title',
        ),
        migrations.RemoveField(
            model_name='note',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='notefile',
            name='lecture_number',
        ),
        migrations.RemoveField(
            model_name='notefile',
            name='lecture_title',
        ),
        migrations.RemoveField(
            model_name='notefile',
            name='subject',
        ),
        migrations.AddField(
            model_name='note',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Lecture'),
        ),
        migrations.AddField(
            model_name='notefile',
            name='lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.Lecture'),
        ),
    ]
