# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 09:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20180107_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('content', models.TextField(max_length=1000)),
                ('answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NoteReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('content', models.TextField(max_length=1000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='notes.NoteQuestion')),
            ],
        ),
        migrations.RenameField(
            model_name='note',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='notequestion',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='notes.Note'),
        ),
    ]
