# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20180108_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(default='blankcourse', max_length=250),
            preserve_default=False,
        ),
    ]
