# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_lecture_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(default='blanknote', max_length=250),
            preserve_default=False,
        ),
    ]
