# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_note_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notequestion',
            name='title',
            field=models.CharField(default='blankquestion', max_length=250),
            preserve_default=False,
        ),
    ]
