# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_notequestion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notequestion',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notereply',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
