# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20180108_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notefile',
            old_name='name',
            new_name='title',
        ),
    ]
