# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0013_auto_20180109_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
