# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0014_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefile',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
