# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanned',
            name='name',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
    ]
