# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_scanned_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cropped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
