# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_cropped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropped',
            name='content',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
