# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_auto_20180109_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cropped',
        ),
        migrations.DeleteModel(
            name='Scanned',
        ),
    ]
